spring:
  datasource:
    url: jdbc:mysql://localhost:3306/spinner_app
    username: root
    password: Menbilirem10#
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    database-platform: org.hibernate.dialect.MySQL5Dialect
    generate-ddl: true
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      format_sql: true
  servlet:
    multipart:
      enabled: true
      file-size-threshold: 2KB
      max-file-size: 500MB
      max-request-size: 1000MB


security:
  jwtProperties:
    secret: VGhpcyBpcyBteSBzZWNyZXQga2V5IGFuZCBteSBzZWNyZXQga2V5IGlzIHZlcnkgdmVyeSBzZWN1cmUuSGVsbG8gTXkgbmFtZSBpcyBBc2lmIGFuZCBpIGFtIGUgZW5naW5lZXI=
    token-validity-in-seconds: 86400
    token-validity-in-seconds-for-remember-me: 604800
  cors:
    allowed-origins: '*'
    allowed-methods: '*'
    allowed-headers: '*'
    exposed-headers: 'Authorization,Link,X-Total-Count'
    allow-credentials: true
    max-age: 1800

application:
  swagger:
    title: CDP API
    description: Core Development Center.
    version: 0.0.1